
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analyzer;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int NUM = 2;
  public static final int LBRACE = 11;
  public static final int INT = 4;
  public static final int MAIN = 6;
  public static final int SEMI = 8;
  public static final int EOF = 0;
  public static final int ID = 3;
  public static final int ASSIGN = 7;
  public static final int error = 1;
  public static final int RPAREN = 10;
  public static final int RETURN = 5;
  public static final int RBRACE = 12;
  public static final int LPAREN = 9;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "NUM",
  "ID",
  "INT",
  "RETURN",
  "MAIN",
  "ASSIGN",
  "SEMI",
  "LPAREN",
  "RPAREN",
  "LBRACE",
  "RBRACE"
  };
}

